package:
  name: wofpy
  version: 0.0.0

source:
  path: ../

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - configparser  # [py2k]
    - docopt
    - flask
    - jinja2
    - lxml
    - python-dateutil
    - pytz
    - spyne

test:
  imports:
    - wof
    - wof.apps
    - wof.flask
  source_files:
    - wof
    - test
  requires:
    - pytest
    - odm2api
    #- pyodbc
    - requests
    - sqlalchemy
    - suds-jurko
    #- uwsgi
    #- geoalchemy-odm2
  commands:
    - python wof/examples/flask/cbi/build_cbi_cache.py || exit 1
    #- START /B /WAIT python wof/examples/flask/swis/runserver_swis.py --config=./test/test_swis_config2.cfg --connection=sqlite:///./test/test_swis2.db || exit 1
    - py.test -s -rxs -v -k "not test_odm2_dao_sqlite"
